import Employee from "../models/Employee.js";
import bcrypt from "bcrypt";
import User from "../models/User.js";
import Attendance from "../models/Attendance.js";
import LeaveApplication from "../models/LeaveApplication.js";
import Payslip from "../models/Payslip.js";
import { generateTemporaryPassword } from "../utils/generatePassword.js";


// =======================
// GET EMPLOYEES
// GET /api/employees
// =======================

export const getEmployees = async (req, res) => {
  try {
    const { department } = req.query;

    // Deleted employees are hard-removed, so nobody should ever see one.
    // The isDeleted filter stays only to hide any legacy soft-deleted rows.
    const where = { isDeleted: { $ne: true } };
    if (department) where.department = department;

    const employees = await Employee.find(where)
      .sort({ createdAt: -1 })
      .populate("userId", "email role")
      .lean();

    const result = employees.map((emp) => ({
      ...emp,
      id: emp._id.toString(),
      user: emp.userId
        ? {
            email: emp.userId.email,
            role: emp.userId.role,
          }
        : null,
    }));

    return res.json(result);
  } catch (error) {
    console.error("Fetch employees error:", error);
    return res.status(500).json({
      error: "Failed to fetch employees",
    });
  }
};


// =======================
// CREATE EMPLOYEE
// POST /api/employees
// =======================

export const createEmployee = async (req, res) => {
  try {
    const {
      firstName,
      lastName,
      email,
      phone,
      position,
      department,
      basicSalary,
      allowances,
      deductions,
      joinDate,
      role,
      bio,
    } = req.body;

    const profilePicture = req.file
      ? `data:${req.file.mimetype};base64,${req.file.buffer.toString("base64")}`
      : "";

    // validation — the password is generated by the system, not supplied
    if (!email || !firstName || !lastName) {
      return res.status(400).json({
        error: "Missing required fields",
      });
    }

    // generate a secure temporary password and hash it (never stored plain)
    const temporaryPassword = generateTemporaryPassword();
    const hashed = await bcrypt.hash(temporaryPassword, 10);

    // create user — must change the temporary password on first login
    const user = await User.create({
      email,
      password: hashed,
      role: role || "EMPLOYEE",
      mustChangePassword: true,
    });

    // create employee
    const employee = await Employee.create({
      userId: user._id,
      firstName,
      lastName,
      email,
      phone,
      position,
      department: department || "Engineering",
      basicSalary: Number(basicSalary) || 0,
      allowances: Number(allowances) || 0,
      deductions: Number(deductions) || 0,
      joinDate: joinDate ? new Date(joinDate) : undefined,
      bio: bio || "",
      profilePicture,
    });

    // return the plaintext temporary password ONCE so the employer can share it
    return res.status(201).json({
      success: true,
      employee,
      temporaryPassword,
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({
        error: "Email already exists",
      });
    }

    console.error("Create employee error:", error);

    return res.status(500).json({
      error: "Failed to create employee",
    });
  }
};


// =======================
// UPDATE EMPLOYEE
// PUT /api/employees/:id
// =======================

export const updateEmployee = async (req, res) => {
  try {
    const { id } = req.params;

    const {
      firstName,
      lastName,
      email,
      phone,
      position,
      department,
      basicSalary,
      allowances,
      deductions,
      password,
      role,
      bio,
      employmentStatus,
    } = req.body;

    const employee = await Employee.findById(id);

    if (!employee) {
      return res.status(404).json({
        error: "Employee not found",
      });
    }

    // update employee
    const employeeUpdate = {
      firstName,
      lastName,
      email,
      phone,
      position,
      department: department || "Engineering",
      basicSalary: Number(basicSalary) || 0,
      allowances: Number(allowances) || 0,
      deductions: Number(deductions) || 0,
      employmentStatus: employmentStatus || "ACTIVE",
      bio: bio || "",
    };

    if (req.file) {
      employeeUpdate.profilePicture = `data:${req.file.mimetype};base64,${req.file.buffer.toString("base64")}`;
    }

    await Employee.findByIdAndUpdate(
      id,
      employeeUpdate,
      { new: true }
    );

    // update user
    const userUpdate = {};

    if (email) userUpdate.email = email;
    if (role) userUpdate.role = role;
    if (password) {
      userUpdate.password = await bcrypt.hash(password, 10);
    }

    await User.findByIdAndUpdate(employee.userId, userUpdate);

    return res.json({
      success: true,
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({
        error: "Email already exists",
      });
    }

    console.error("Update employee error:", error);

    return res.status(500).json({
      error: "Failed to update employee",
    });
  }
};


// =======================
// DELETE EMPLOYEE (HARD DELETE + CASCADE)
// DELETE /api/employees/:id
// =======================

export const deleteEmployee = async (req, res) => {
  try {
    const { id } = req.params;

    const employee = await Employee.findById(id);

    if (!employee) {
      return res.status(404).json({
        error: "Employee not found",
      });
    }

    // safety: an admin cannot delete their own linked account
    if (
      employee.userId &&
      employee.userId.toString() === req.session?.userId
    ) {
      return res.status(400).json({
        error: "You cannot delete your own account",
      });
    }

    // cascade: remove records that reference this employee so we don't
    // leave orphaned attendance / leave / payslip documents behind
    await Promise.all([
      Attendance.deleteMany({ employeeId: employee._id }),
      LeaveApplication.deleteMany({ employeeId: employee._id }),
      Payslip.deleteMany({ employeeId: employee._id }),
    ]);

    // remove the linked user (login) account
    if (employee.userId) {
      await User.findByIdAndDelete(employee.userId);
    }

    // remove the employee record itself
    await Employee.findByIdAndDelete(employee._id);

    return res.json({
      success: true,
    });
  } catch (error) {
    console.error("Delete employee error:", error);

    return res.status(500).json({
      error: "Failed to delete employee",
    });
  }
};